### ISSUE TITLE
비밀번호 암호화

### ISSUE THREAD

**Issue by jeangho293** [jangjiyu/H99-W3-nodejs_Blog#4]
https://github.com/jangjiyu/H99-W3-nodejs_Blog/blob/dd8104d932c28ba894ac0b8a5823f4ede5b14405/routes/posts.js#L26

현재 암호화까지는 필요하지는 않겠지만,
실 서비스에서 비밀번호는 DB에 plain하게 저장하지않습니다.
DB가 유출되는 경우, 고스란히 비밀번호가 유출되기 때문에 암호화를 해줍니다.
단방향 암호화에 대해서 한번 알아보고 적용해보면 도움이 될 것입니다.

**Comment by jangjiyu** [comment]
넵!
